/**
 * BJavaDecompiler
 * Copyright 2026 Jose Rodriguez <jrpcone@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Developer: Jose Rodriguez <jrpcone@gmail.com>
 */

/**
 * BJavaDecompiler - AI delegation worker authentication.
 *
 * The AiWindowsAssistant worker isn't a browser session — it has no cookie/JWT, just a static
 * bearer token generated by AiDelegationService and copied into its own .env once. Mirrors
 * SysAdminCenterHCP's escalationAuth.ts exactly. Applied only to /api/ai-delegation/worker/*.
 */

import { Request, Response, NextFunction } from 'express';
import { AiDelegationService } from '../services/aiDelegationService';
import { Logger } from '../core/logger';

const logger = Logger.getLogger('AiDelegationAuth');

export function aiDelegationWorkerAuthMiddleware(req: Request, res: Response, next: NextFunction): void {
  const authHeader = req.headers.authorization;
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    res.status(401).json({ success: false, error: 'Unauthorized — no worker token provided' });
    return;
  }
  const token = authHeader.substring(7);
  const expected = AiDelegationService.getOrCreateWorkerApiKey();
  if (token !== expected) {
    logger.debug('AI delegation worker request rejected — token mismatch');
    res.status(401).json({ success: false, error: 'Invalid worker token' });
    return;
  }
  next();
}
